server:
  port: 9005

spring:
  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # (1) 스키마 생성
    show-sql: true # (2) SQL 쿼리 출력
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true # (3) SQL pretty print

      defer-datasource-initialization: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${application.spring.datasource.url}
    username: ${application.spring.datasource.username}
    password: ${application.spring.datasource.password}


# 모니터링
management:
  endpoints:
    web:
      base-path: /mypage-service/actuator
      exposure:
        include: refresh, beans, health, info, metrics, prometheus  # 노출할 Actuator 엔드포인트 목록
  endpoint:
    health:
      show-details: always  # 모든 세부사항을 항상 표시
  prometheus:
    metrics:
      export:
        enabled: true